### ISSUE TITLE
Shows a blank white screen with no information whatsoever

### ISSUE THREAD

**Issue by ananyacleetus** [KjellConnelly/react-native-musicplayercontroller#2]
It shows a blank screen and then an alert cancel popup.

MusicPlayerController.presentPicker((metadata)=>{
// Successfully saved MPMediaItemCollection to NSUserDefaults.
// Returns an array of metadata for each track (not all MPMediaItem
// fields are copied, only the blantantly needed ones)
alert(metadata[0]["title"])
}, ()=>{
// Opened, but user tapped Cancel
alert("Cancel")
})

**Comment by KjellConnelly** [comment]
Not really sure what the problem is. Did you follow the instructions fully and add the key to info.plist?

Also, are you using a regular React native app with just one view controller? The apps I've tested this on only use one view controller (new view controllers are faked, and use JavaScript. They're not native ones). So it's possibly that the code is trying to present the picker from the roof view controller, but it's not actually finding a referencing to the currently displayed native view controller.
